{{ config(materialized='table') }}

SELECT
    "ID",
    "Name", 
    "LongName",
    "photoUrl",
    "playerUrl",
    "Nationality",
    "Age",
    "POT" AS "Potential",
    "Club",
    "Contract",
    "Positions",
    "Height",
    "Weight",
    "Preferred Foot",
    "BOV" AS "Best Overall",
    "Best Position",
    "Joined",
    "Loan Date End",
    "Value",
    "Wage",
    "Release Clause",
    "Attacking",
    "Crossing",
    "Finishing",
    "Heading Accuracy",
    "Short Passing",
    "Volleys",
    "Skill",
    "Dribbling",
    "Curve",
    "FK Accuracy",
    "Long Passing",
    "Ball Control",
    "Movement",
    "Acceleration",
    "Sprint Speed",
    "Agility",
    "Reactions",
    "Balance",
    "Power",
    "Shot Power",
    "Jumping",
    "Stamina",
    "Strength",
    "Long Shots",
    "Mentality",
    "Aggression",
    "Interceptions",
    "Positioning",
    "Vision",
    "Penalties",
    "Composure",
    "Defending",
    "Marking",
    "Standing Tackle",
    "Sliding Tackle",
    "Goalkeeping",
    "GK Diving",
    "GK Handling",
    "GK Kicking",
    "GK Positioning",
    "GK Reflexes",
    "Total Stats",
    "Base Stats",
    "W/F" AS "Weak Foot",
    "SM" AS "Skill Moves",
    "A/W" AS "Attacking Workrate",
    "D/W" AS "Defensive Workrate",
    "IR" AS "International Reputation",
    "PAC",
    "SHO",
    "PAS",
    "DRI",
    "DEF",
    "PHY",
    "Hits"
FROM {{ source('public', 'my_table2') }}
LIMIT 1
