{{ config(materialized='table') }}

WITH first_cleaning AS (
    SELECT
        "ID" AS "id"
        , "Name" AS "name"
        , "Nationality" AS "nationality"
        , "Age" AS "age"
        , "↓OVA" AS "ova"
        , {{ remove_newlines('"Club"') }} AS "club"
        , "POT" AS "pot"
        , "Contract" AS "contract"
        , {{ define_contract_type('"Contract"') }} AS "type_of_contract"
        , {{ start_time_contract('"Contract"') }} AS "start_year"
        , "Positions" AS "positions"
        , {{ strip_affix('"Height"', 'cm') }} AS "height" 
        , {{ strip_affix('"Weight"', 'kg') }} AS "weight"
        , "Preferred Foot" AS "preferred_foot"
        , "BOV" AS "bov"
        , "Best Position" AS "best_position"
        , "Joined" AS "joined"
        , "Loan Date End" AS "loan_date_end"
        , "Value" AS "value"
        , "Wage" AS "wage"
        , "Release Clause" AS "release_clause"
        , CAST("Attacking" / 5 AS INT) AS "attacking"
        , "Crossing" AS "crossing"
        , "Finishing" AS "finishing"
        , "Heading Accuracy" AS "heading_accuracy"
        , "Short Passing" AS "short_passing"
        , "Volleys" AS "volleys"
        , CAST("Skill" / 5 AS INT) AS "skill"
        , "Dribbling" AS "dribbling"
        , "Curve" AS "curve"
        , "FK Accuracy" AS "fk_accuracy"
        , "Long Passing" AS "long_passing"
        , "Ball Control" AS "ball_control"
        , CAST("Movement" / 5 AS INT) AS "movement"
        , "Acceleration" AS "acceleration"
        , "Sprint Speed" AS "sprint_speed"
        , "Agility" AS "agility"
        , "Reactions" AS "reactions"
        , "Balance" AS "balance"
        , CAST("Power" / 5 AS INT) AS "power"
        , "Shot Power" AS "shot_power"
        , "Jumping" AS "jumping"
        , "Stamina" AS "stamina"
        , "Strength" AS "strength"
        , "Long Shots" AS "long_shots"
        , CAST("Mentality" / 6 AS INT) AS "mentality"
        , "Aggression" AS "aggression"
        , "Interceptions" AS "interceptions"
        , "Positioning" AS "positioning"
        , "Vision" AS "vision"
        , "Penalties" AS "penalties"
        , "Composure" AS "composure"
        , CAST("Defending" / 3 AS INT) AS "defending"
        , "Marking" AS "marking"
        , "Standing Tackle" AS "standing_tackle"
        , "Sliding Tackle" AS "sliding_tackle"
        , CAST("Goalkeeping" / 5 AS INT) AS "goalkeeping"
        , "GK Diving" AS "gk_diving"
        , "GK Handling" AS "gk_handling"
        , "GK Kicking" AS "gk_kicking"
        , "GK Positioning" AS "gk_positioning"
        , "GK Reflexes" AS "gk_reflexes"
        , "Total Stats" AS "total_stats"
        , "Base Stats" AS "base_stats"
        , {{ strip_affix('"W/F"', '★') }} AS "w/f"
        , {{ strip_affix('"SM"', '★') }} AS "sm"
        , "A/W" AS "a/w"
        , "D/W" AS "d/w"
        , {{ strip_affix('"IR"', '★') }} AS "ir"
        , "PAC" AS "pac"
        , "SHO" AS "sho"
        , "PAS" AS "pas"
        , "DRI" AS "dri"
        , "DEF" AS "def"
        , "PHY" AS "phy"
        , {{ convert_hits('"Hits"') }} AS "hits"
    FROM {{ source('public', 'fifa_model_elt') }}
), second_cleaning AS (
    SELECT
        *
        , {{ ft_to_cm('"height"') }} AS "height_cm"
        , {{ lbs_to_kg('"weight"') }} AS "weight_kg"
        , {{ format_money('"value"') }} / 1000000 AS "value_in_euro_millions"
        , {{ format_money('"wage"') }} AS "wage_in_euros"
        , {{ format_money('"release_clause"') }} / 1000000 AS "release_clause_in_euro_millions"
        , {{ end_contract('"type_of_contract"', '"contract"', '"loan_date_end"') }} AS "end_year"
    FROM first_cleaning
)

SELECT
    *
FROM second_cleaning