WITH raw_data AS (
    SELECT
        "ID"
        , "Name"
        , "LongName"
        , "photoUrl"
        , "playerUrl"
        , "Nationality"
        , "Age"
        , "POT"
        , "Contract"
        , {{ define_contract_type('"Contract"') }} AS "Type of Contract"
        , {{ start_time_contract('"Contract"') }} AS "Start Year"
        , "Positions"
        , {{ strip_suffix('"Height"', 'cm') }} AS "Height"
        , {{ strip_suffix('"Weight"', 'kg') }} AS "Weight"
        , "Preferred Foot"
        , "BOV"
        , "Best Position"
        , "Joined"
        , "Loan Date End"
        , "Value"
        , "Wage"
        , "Release Clause"
        , CAST("Attacking" / 5 AS INT) AS "Attacking"
        , "Crossing"
        , "Finishing"
        , "Heading Accuracy"
        , "Short Passing"
        , "Volleys"
        , CAST("Skill" / 5 AS INT) AS "Skill"
        , "Dribbling"
        , "Curve"
        , "FK Accuracy"
        , "Long Passing"
        , "Ball Control"
        , CAST("Movement" / 5 AS INT) AS "Movement"
        , "Acceleration"
        , "Sprint Speed"
        , "Agility"
        , "Reactions"
        , "Balance"
        , CAST("Power" / 5 AS INT) AS "Power"
        , "Shot Power"
        , "Jumping"
        , "Stamina"
        , "Strength"
        , "Long Shots"
        , CAST("Mentality" / 6 AS INT) AS "Mentality"
        , "Aggression"
        , "Interceptions"
        , "Positioning"
        , "Vision"
        , "Penalties"
        , "Composure"
        , CAST("Defending" / 3 AS INT) AS "Defending"
        , "Marking"
        , "Standing Tackle"
        , "Sliding Tackle"
        , CAST("Goalkeeping" / 5 AS INT) AS "Goalkeeping"
        , "GK Diving"
        , "GK Handling"
        , "GK Kicking"
        , "GK Positioning"
        , "GK Reflexes"
        , "Total Stats"
        , "Base Stats"
        , {{ strip_suffix('"W/F"', '★') }} AS "W/F"
        , {{ strip_suffix('"SM"', '★') }} AS "SM"
        , "A/W"
        , "D/W"
        , {{ strip_suffix('"IR"', '★') }} AS "IR"
        , "PAC"
        , "SHO"
        , "PAS"
        , "DRI"
        , "DEF"
        , "PHY"
        , {{ convert_hits('"Hits"') }} AS "Hits"
    FROM {{ source('public', 'fifa_model_elt') }}
), cleaning AS (
    SELECT
        *
        , {{ ft_to_cm('"Height"') }} AS "height_cm"
        , {{ lbs_to_kg('"Weight"') }} AS "weight_kg"
        , {{ format_money('"Value"') }} / 1000000 AS "value_in_euro_millions"
        , {{ format_money('"Wage"') }} AS "wage_in_euros"
        , {{ format_money('"Release Clause"') }} / 1000000 AS "release_clause_in_euro_millions"
        , {{ end_contract('"Type of Contract"', '"Contract"', '"Loan Date End"') }} AS "end_year"
    FROM raw_data
) SELECT {{ rename_columns('cleaning') }} FROM cleaning
