WITH raw_data AS (
    SELECT
        "ID"
        , "Name"
        , "LongName"
        , "photoUrl"
        , "playerUrl"
        , "Nationality"
        , "Age"
        , "POT"
        , "Club"
        , "Contract"
        , "Positions"
        , {{ strip_suffix('"Height"', 'cm') }} AS "Height"
        , {{ strip_suffix('"Weight"', 'kg') }} AS "Weight"
        , "Preferred Foot"
        , "BOV"
        , "Best Position"
        , "Joined"
        , "Loan Date End"
        , "Value"
        , "Wage"
        , "Release Clause"
        , "Attacking"
        , "Crossing"
        , "Finishing"
        , "Heading Accuracy"
        , "Short Passing"
        , "Volleys"
        , "Skill"
        , "Dribbling"
        , "Curve"
        , "FK Accuracy"
        , "Long Passing"
        , "Ball Control"
        , "Movement"
        , "Acceleration"
        , "Sprint Speed"
        , "Agility"
        , "Reactions"
        , "Balance"
        , "Power"
        , "Shot Power"
        , "Jumping"
        , "Stamina"
        , "Strength"
        , "Long Shots"
        , "Mentality"
        , "Aggression"
        , "Interceptions"
        , "Positioning"
        , "Vision"
        , "Penalties"
        , "Composure"
        , "Defending"
        , "Marking"
        , "Standing Tackle"
        , "Sliding Tackle"
        , "Goalkeeping"
        , "GK Diving"
        , "GK Handling"
        , "GK Kicking"
        , "GK Positioning"
        , "GK Reflexes"
        , "Total Stats"
        , "Base Stats"
        , "W/F"
        , "SM"
        , "A/W"
        , "D/W"
        , "IR"
        , "PAC"
        , "SHO"
        , "PAS"
        , "DRI"
        , "DEF"
        , "PHY"
        , "Hits"
    FROM {{ source('public', 'fifa_model_elt') }}
)

SELECT
    *
    , {{ ft_to_cm('raw_data."Height"') }} AS "height_cm"
    , {{ lbs_to_kg('raw_data."Weight"') }} AS "weight_kg"
FROM raw_data
